var requireDir = require('require-dir');

//Read all dir of tasks and return as an object
var availableTasks = requireDir('../widgets/', { recurse: true });

var tasks = [],  taskObject; 

Object.keys(availableTasks).forEach(function(key) {
    if(availableTasks[key].index) {
        setTask(availableTasks[key].index);
    } else {
        var tasksArray = [];
        Object.keys(availableTasks[key]).forEach(function(k) {
            findTasks(availableTasks[key][k], tasksArray);  
        });

        if(tasksArray.length > 0) {
            tasksArray.forEach(function(task) {
                setTask(task.index);
            })
        }
    }
});

function setTask(task) {
    taskObject = task;//main loaded module without the filetype suffix (the index.js file)
    
    if (!taskObject.excludeFromSeries) {
        tasks.push(taskObject.task);//task attribute is generated by the requireDir module
    } 
}

function findTasks(task, taskArray) {
    if(task.index) {
        taskArray.push(task);
    } else {
        Object.keys(task).forEach(function(key) {
            findTasks(task[key], taskArray)
        });
    }
}

module.exports =  tasks;